### ISSUE TITLE
“fixed” height for conference panel on conference-list-page

### ISSUE THREAD

**Issue by SteffiPeTaffy** [SteffiPeTaffy/conference-rating#20]
The height of a conference panel should be the same, independent from the data provided by the user. Right now conferences with no link to the conference home page are slightly smaller than others. Keep in mind that the panel should be responsive :)

**Comment by SteffiPeTaffy** [comment]
<img width="932" alt="screen shot 2015-10-12 at 20 27 19" src="https://cloud.githubusercontent.com/assets/739104/10435322/8e9a60fe-711f-11e5-900e-66dc3204e4d8.png">

**Comment by ImmoStanke** [comment]
We couldn't reproduce the issue in Chrome, Firefox or Safari. Please check if it still exists.
