### ISSUE TITLE
Show previous rating for upcoming conferences

### ISSUE THREAD

**Issue by SteffiPeTaffy** [SteffiPeTaffy/conference-rating#40]
For an upcoming conference, it would be really helpful to see the previous rating, e.g. best case from the same conference (identified by series tag) from the years before.

We need to indicate to the user, that this is a previous rating. Ideas: lighter colors & show year of rating.

**Comment by sroidl** [comment]
We implemented an average rating of all past conferences in the series. This is displayed in the conference list and in the detail page.
