### ISSUE TITLE
Special characters in location show up escaped, non-latin characters become question marks

### ISSUE THREAD

**Issue by flosell** [SteffiPeTaffy/conference-rating#94]
The location field (probably others as well) can't handle special characters (like `&`) and non-latin characters: 

<img width="626" alt="screen shot 2018-06-03 at 09 27 16" src="https://user-images.githubusercontent.com/540525/40882577-cad422f0-6710-11e8-8302-a6d46bf3703b.png">

Was supposed to be "Growth cafe & co. - 236/8-9 ซอย สยามสแควร์ 2 Khwaeng Pathum Wan, Khet Pathum Wan, Krung Thep Maha Nakhon 10330"

**Comment by flosell** [comment]
Thanks @marcos-mercuri-tw for fixing the special character issue! 

Re-opening this as the `&` characters aren't fixed yet: 
![Screenshot 2020-04-02 at 09 05 23](https://user-images.githubusercontent.com/540525/78203477-472f1700-74c1-11ea-8899-d3c7658e8050.png)

**Comment by m-mercuri** [comment]
Hi, @flosell, 
For what I could see the `&` (and other html characters) is being escaped [here](https://github.com/SteffiPeTaffy/conference-rating/blob/master/src/clj/conference_rating/handler.clj#L78).
I see the commit was to address this [issue](https://github.com/SteffiPeTaffy/conference-rating/issues/52), Was this trying to fix a specific bug?

**Comment by flosell** [comment]
Hi @marcos-mercuri-tw, I believe this was done as a quick way to address a concern in our security review, storing unsafe characters in the DB. This could probably be improved though. 

I'll forward our discussion with the reviewers via E-Mail for more details.

**Comment by flosell** [comment]
Fixed in #96, thanks @marcos-mercuri-tw !
